/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dragondungeongame;

import static dragondungeongame.DragonDungeonGame.frame;
import java.awt.BorderLayout;
import java.awt.Dimension;
import static javax.swing.JFrame.EXIT_ON_CLOSE;

/**
 *
 * @author Shannon
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    public String userName = "";
    javax.swing.JFrame frame = new javax.swing.JFrame();
    javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
    javax.swing.JButton start = new javax.swing.JButton();
    javax.swing.JLabel instructionLabel = new javax.swing.JLabel();
    
    public StartPage() {
        initComponents();
        
        nameConfirmButton.addActionListener( (e) -> {
            submitAction();
            moveToInstructions();
        });
        
        start.addActionListener( (e) -> {
            //System.out.println("Frame Switch");
            setVisible(false);
            callMaze();
            //set invisible when player reaches end
            //callTrivia();
        });
    }
    
    private void submitAction() {
       userName = userNameTextField.getText();
       System.out.println(userName);
       //do something with the variabe userWord here (print it to the console, etc.)
    }

    private void callTrivia(){
        DragonDungeonGame.frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        DragonDungeonGame.frame.setPreferredSize(new Dimension(630, 700));
        DragonDungeonGame.frame.setLayout(new BorderLayout());
        DragonDungeonGame.frame.add(DragonDungeonGame.df, BorderLayout.CENTER);
        DragonDungeonGame.frame.pack();
        DragonDungeonGame.frame.repaint();

    }
    
    private void moveToInstructions(){
        remove(jPanel1);
        add(jPanel2);
        validate();
        initComponents2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameConfirmButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        titleCard = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        nameConfirmButton.setText("OK");
        jPanel1.add(nameConfirmButton);
        nameConfirmButton.setBounds(713, 359, 49, 25);

        nameLabel.setText("Player Name:");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(280, 360, 90, 22);
        jPanel1.add(userNameTextField);
        userNameTextField.setBounds(387, 356, 308, 30);

        titleCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dragondungeongame/cooltext269235969265810.png"))); // NOI18N
        titleCard.setText("jLabel1");
        jPanel1.add(titleCard);
        titleCard.setBounds(110, 120, 800, 150);

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dragondungeongame/bg.jpg"))); // NOI18N
        bgImage.setText("jLabel1");
        jPanel1.add(bgImage);
        bgImage.setBounds(0, 0, 1030, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initComponents2(){
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel2.setLayout(null);
        
        start.setText("Start");
        jPanel2.add(start);
        start.setBounds(850, 550, 100, 25);
        
        instructionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dragondungeongame/cooltext269242352137886.png"))); // NOI18N
        instructionLabel.setText("jLabel1");
        jPanel2.add(instructionLabel);
        instructionLabel.setBounds(30, 80, 950, 360);
        
        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dragondungeongame/bg.jpg"))); // NOI18N
        bgImage.setText("jLabel1");
        jPanel2.add(bgImage);
        bgImage.setBounds(0, 0, 1030, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
}
    
    public void callMaze(){
        new DragonDungeonGame();
    }
    /**
     * @param args the command line arguments
     */
  //  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nameConfirmButton;
    private javax.swing.JTextField nameLabel;
    private javax.swing.JLabel titleCard;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables

    
}
